stages:
  - build
  - trigger

.download_script: &download_script
  - curl --location --header "PRIVATE-TOKEN:$ACCESS_TOKEN" --silent https://gitlab.com/api/v4/snippets/1796163/raw | tr -d '\r' > download.sh

.build:
  stage: build
  before_script: *download_script
  script:
    - sh download.sh vendor master vendor:${MZNARCH} vendor.zip
    - unzip -q vendor.zip
    - sh download.sh minizinc develop build:${MZNARCH} minizinc.zip
    - unzip -q minizinc.zip
    - cmake -S . -B build -G"$CMAKE_ARCH" -DCMAKE_BUILD_TYPE=Release -DUSE_SYSTEM_LIBMINIZINC=1 -Dlibminizinc_DIR=$CI_PROJECT_DIR/minizinc/$CMAKEDIR -DGecode_ROOT="$CI_PROJECT_DIR/vendor/gecode" -DGurobi_ROOT="$CI_PROJECT_DIR/vendor/gurobi" -DCPlex_ROOT="$CI_PROJECT_DIR/vendor/CPLEX_Studio/cplex" -DOsiCBC_ROOT="$CI_PROJECT_DIR/vendor/cbc" -DSCIP_ROOT="$CI_PROJECT_DIR/vendor/scip" -DXpress_ROOT="$CI_PROJECT_DIR/vendor/xpressmp" -DCMAKE_INSTALL_PREFIX="$CI_PROJECT_DIR/findMUS" 
    - cmake --build build --config Release --target install
  artifacts:
    paths:
      - findMUS/
  cache:
    key: "$CI_JOB_NAME"
    paths: [minizinc.zip*, vendor.zip*]

build:linux:
  extends: .build
  image: dekker1/minibuild:cpp
  variables:
    MZNARCH: "linux"
    CMAKE_ARCH: "Ninja"
    CMAKEDIR: "lib/cmake/libminizinc"
  tags: [linux, docker]

build:osx:
  extends: .build
  variables:
    MZNARCH: "osx"
    CMAKE_ARCH: "Ninja"
    CMAKEDIR: "lib/cmake/libminizinc"
  tags: [osx, cmake, cpp]

build:win64:
  extends: .build
  variables:
    MZNARCH: "win64"
    CMAKEDIR: "CMake/libminizinc"
    CMAKE_ARCH: "Visual Studio 15 2017 Win64"
  before_script:
    - curl -o download.sh --location --header "PRIVATE-TOKEN:%ACCESS_TOKEN%" --silent https://gitlab.com/api/v4/snippets/1796163/raw
    - dos2unix download.sh
  script:
    - sh download.sh vendor master vendor:%MZNARCH% vendor.zip
    - unzip -q vendor.zip
    - sh download.sh minizinc develop build:%MZNARCH% minizinc.zip
    - unzip -q minizinc.zip
    - cmake -S . -B build -G"%CMAKE_ARCH%" -DCMAKE_BUILD_TYPE=Release -DUSE_SYSTEM_LIBMINIZINC=1 -Dlibminizinc_DIR="%CI_PROJECT_DIR%/minizinc/%CMAKEDIR%" -DGecode_ROOT="%CI_PROJECT_DIR%/vendor/gecode" -DGurobi_ROOT="%CI_PROJECT_DIR%/vendor/gurobi" -DCPlex_ROOT="%CI_PROJECT_DIR%/vendor/CPLEX_Studio/cplex" -DOsiCBC_ROOT="%CI_PROJECT_DIR%/vendor/cbc" -DSCIP_ROOT="%CI_PROJECT_DIR%/vendor/scip" -DXpress_ROOT="%CI_PROJECT_DIR%/vendor/xpressmp" -DCMAKE_INSTALL_PREFIX="%CI_PROJECT_DIR%/findMUS"
    - cmake --build build --config Release --target install
  tags: [win64, cmake, cpp]

# ----------- Trigger MiniZincIDE pipeline -----------

trigger:ide:
  stage: trigger
  trigger:
    project: minizinc/minizinc-ide
    branch: develop
  only: [develop]
